<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: 1.0
Change history:
0.1 (01.09.2016): Initial draft
0.2 (13.09.2016): Request-/ProvideUserDetails changed from synchronous to asynchronous communication
0.3 (09.11.2016): Namespaces updated
0.4 (23.11.2016): Description of the interface moved to the Backend Interface Specification
1.0 (23.06.2017): Namespaces updated
-->
<wsdl:definitions
    name="ProvideUserDetailsService"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:cm="http://tsystems.com/etccm/iso12855/common"
    xmlns:tns="http://tsystems.com/etccm/iso12855/userDetails"
    targetNamespace="http://tsystems.com/etccm/iso12855/userDetails">

    <wsdl:documentation>
        Copyright (c) 2015 T-Systems International GmbH
        All Rights Reserved

        This software is the confidential and proprietary information of
        T-Systems International GmbH ("Confidential Information").
        You shall not disclose such Confidential Information and shall
        use it only in accordance with the terms of the license agreement
        you entered into with T-Systems International GmbH.
    </wsdl:documentation>

    <wsdl:types>
        <xsd:schema targetNamespace="http://tsystems.com/etccm/iso12855/userDetails">
            <xsd:import schemaLocation="Common.xsd" namespace="http://tsystems.com/etccm/iso12855/common" />
            <xsd:include schemaLocation="UserDetails.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="userDetailsRequest">
        <wsdl:part name="request" element="tns:InfoExchangeProvideUserDetails" />
    </wsdl:message>

    <wsdl:message name="userDetailsResponse">
        <wsdl:part name="response" element="cm:response" />
    </wsdl:message>

    <wsdl:portType name="ProvideUserDetailsServicePT">
        <wsdl:operation name="provideUserDetails">
            <wsdl:input message="tns:userDetailsRequest" />
            <wsdl:output message="tns:userDetailsResponse" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="ProvideUserDetailsServiceBinding" type="tns:ProvideUserDetailsServicePT">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="provideUserDetails">
            <soap:operation soapAction="http://tsystems.com/etccm/iso12855/ProvideUserDetailsService/provideUserDetails" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="ProvideUserDetailsService">
        <wsdl:port name="ProvideUserDetailsServicePort" binding="tns:ProvideUserDetailsServiceBinding">
            <soap:address location="http://localhost/ProvideUserDetailsService" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
