<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: 1.0
Change history:
0.1 (22.05.2017): Initial draft
1.0 (23.06.2017): Namespaces updated
-->
<wsdl:definitions
    name="ProvideComplianceDataService"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:cm="http://tsystems.com/etccm/iso12855/common"
    xmlns:tns="http://tsystems.com/etccm/iso12855/complianceData"
    targetNamespace="http://tsystems.com/etccm/iso12855/complianceData">

    <wsdl:documentation>
        Copyright (c) 2015 T-Systems International GmbH 
        All Rights Reserved 

        This software is the confidential and proprietary information of 
        T-Systems International GmbH ("Confidential Information"). 
        You shall not disclose such Confidential Information and shall 
        use it only in accordance with the terms of the license agreement 
        you entered into with T-Systems International GmbH.
    </wsdl:documentation>

    <wsdl:types>
        <xsd:schema targetNamespace="http://tsystems.com/etccm/iso12855/complianceData">
            <xsd:import schemaLocation="Common.xsd" namespace="http://tsystems.com/etccm/iso12855/common" />
            <xsd:include schemaLocation="ComplianceData.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="complianceDataRequest">
        <wsdl:part name="request" element="tns:InfoExchangeProvideComplianceData" />
    </wsdl:message>

    <wsdl:message name="complianceDataResponse">
        <wsdl:part name="response" element="cm:response" />
    </wsdl:message>

    <wsdl:portType name="ProvideComplianceDataServicePT">
        <wsdl:operation name="provideComplianceData">
            <wsdl:input message="tns:complianceDataRequest" />
            <wsdl:output message="tns:complianceDataResponse" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="ProvideComplianceDataServiceBinding" type="tns:ProvideComplianceDataServicePT">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="provideComplianceData">
            <soap:operation soapAction="http://tsystems.com/etccm/iso12855/ProvideComplianceDataService/provideComplianceData" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="ProvideComplianceDataService">
        <wsdl:port name="ProvideComplianceDataServicePort" binding="tns:ProvideComplianceDataServiceBinding">
            <soap:address location="http://localhost/ProvideComplianceDataService" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
