<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: 1.1
Change history:
0.1 (01.09.2016): Initial draft
0.2 (09.11.2016): Namespaces updated
0.3 (11.11.2016): WhiteListDelta specific validations moved to WhiteListDelta.xsd
0.4 (23.11.2016): Description of the interface moved to the Backend Interface Specification
1.0 (23.06.2017): Namespaces updated
1.1 (29.09.2017): The differen exception list services have now thier own namespace
-->
<wsdl:definitions
    name="WhiteListDeltaService"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:cm="http://tsystems.com/etccm/iso12855/common"
    xmlns:el="http://tsystems.com/etccm/iso12855/exceptionList"
    xmlns:tns="http://tsystems.com/etccm/iso12855/whiteListDelta"
    targetNamespace="http://tsystems.com/etccm/iso12855/whiteListDelta">

    <wsdl:documentation>
        Copyright (c) 2015 T-Systems International GmbH
        All Rights Reserved

        This software is the confidential and proprietary information of
        T-Systems International GmbH ("Confidential Information").
        You shall not disclose such Confidential Information and shall
        use it only in accordance with the terms of the license agreement
        you entered into with T-Systems International GmbH.
    </wsdl:documentation>

    <wsdl:types>
        <xsd:schema targetNamespace="http://tsystems.com/etccm/iso12855/whiteListDelta">
            <xsd:import schemaLocation="Common.xsd" namespace="http://tsystems.com/etccm/iso12855/common" />
            <xsd:import schemaLocation="WhiteListDelta.xsd" namespace="http://tsystems.com/etccm/iso12855/exceptionList" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="exceptionListRequest">
        <wsdl:part name="request" element="el:InfoExchangeExceptionList" />
    </wsdl:message>

    <wsdl:message name="exceptionListResponse">
        <wsdl:part name="response" element="cm:response" />
    </wsdl:message>

    <wsdl:portType name="WhiteListDeltaServicePT">
        <wsdl:operation name="sendWhiteListDelta">
            <wsdl:input message="tns:exceptionListRequest" />
            <wsdl:output message="tns:exceptionListResponse" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="WhiteListDeltaServiceBinding" type="tns:WhiteListDeltaServicePT">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="sendWhiteListDelta">
            <soap:operation soapAction="http://tsystems.com/etccm/iso12855/WhiteListDeltaService/sendWhiteListDelta" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="WhiteListDeltaService">
        <wsdl:port name="WhiteListDeltaServicePort" binding="tns:WhiteListDeltaServiceBinding">
            <soap:address location="http://localhost/WhiteListDeltaService" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
